version: 2

machine:
  java:
    version: oraclejdk8

deployment:
  staging:
    branch: master
    heroku: 
      appname: wargameapp
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
